tree: clear
	@echo "=========================================="
	@echo "             PROGRAMA TREE               "
	@echo "=========================================="
	@echo "Compilando o programa Tree"
	gcc *.c *.h -o tree
	@echo "Tornando o programa Tree executável"
	chmod +x tree
	@echo "Executando o programa Tree"
	./tree
	@echo "=========================================="
clear:
	@echo "=========================================="
	@echo "Removendo os programas compilados"
	@echo "=========================================="
	@echo "Removendo o programa Tree"	
	rm -f Tree
	@echo "=========================================="
help:
	@echo "=========================================="
	@echo "         		AJUDA                    "
	@echo "=========================================="
	@echo "help				| ajuda"
	@echo "Tree			| executa mensagem de teste"
	@echo "clear			| apaga códigos compilados"
