tree: clear
	@echo " ________________________________________"
	@echo "|                                        |"
	@echo "|	Inicializando o Programa	 |"
	@echo "|________________________________________|"
	@gcc *.c *.h -o tree
	@chmod +x tree
	@./tree
clear:
	@rm -f Tree
help:
	@echo " ____________________________________________"
	@echo "|                                            |"
	@echo "|         	     AJUDA                   |"
	@echo "|____________________________________________|"
	@echo "|        |                                   |"
	@echo "|- help  | ajuda                             |"
	@echo "|- Tree  | executa mensagem de teste         |"
	@echo "|- clear | apaga códigos compilados          |"
	@echo "|________|___________________________________|"